! `${ '' [ 0 ] ( ) ?. x }` ; 
+ 0 . x ( ) ?. x ; 
+ { 0 : function ( ) { } ( ) ( ) ?. x } ; 
0 . x ( ) ?. x ; 
0 / ! function ( ) { } ( ) ( ) ?. x ; 
0 / ! function ( ) { } ( ) ( ... 0 ) ?. x ; 
0 > 0n . x ( ) ?. x ; 
0 > [ ] . x ( ) ?. x ; 
0 > `` . x ( ) ?. x ; 
0 > true . x ( ) ?. x ; 
[ 1n . x ( ) ?. x ] ; 
[ [ ] . x ( ) ?. x ] ; 
[ ] . x ( ) ?. x ; 
[ `` . x ( ) ?. x ] ; 
[ true . x ( ) ?. x ] ; 
`` . x ( ) ?. x ; 
class x { static { super [ super [ x ] ( ) ?. x ] ||= x => 0 ; } } 
for ( let x ; ; x ( ) ?. x ) ; 
for ( let x ; x ( ) ?. x ; ) ; 
for ( let x in x = class extends 0 ( ) ?. x { } ) ; 
if ( function ( x , ) { } ( ) ( ) ?. x ) ; 
let x , await = { get 0 ( ) { } , } [ - x ( ) ?. x ] ; 
let x ; - x ( ) ?. x ; 
new class x { 0 = + super [ super . x ( ) ?. x ] ; } ; 
new class { 0 = super [ super . x ( ) ?. x ] ; } ; 
true . x ( ) ?. x ; 
var x = x ( ) ?. x ; 
