~ { [ Symbol . toPrimitive ] : class { } } ; 
0 != { [ Symbol . toPrimitive ] : 0 } ; 
- { [ Symbol . toPrimitive ] : x => [ ] } ; 
- { [ Symbol . toPrimitive ] : 0 } ; 
+ { [ Symbol . toPrimitive ] : 0 } ; 
`${ { [ Symbol . toPrimitive ] : 0 } }` ; 
0 > { [ Symbol . toPrimitive ] : 0 } ; 
0 <= { [ Symbol . toPrimitive ] : 0 } ; 
0 < { [ Symbol . toPrimitive ] : 0 } ; 
- [ { [ Symbol . toPrimitive ] : 0 } ] ; 
0 == { [ Symbol . toPrimitive ] : 0 } ; 
`${ 0 }${ { [ Symbol . toPrimitive ] : 0 } }` ; 
0 + { [ Symbol . toPrimitive ] : 0 } ; 
0 >= { [ Symbol . toPrimitive ] : 0 } ; 
~ { [ Symbol . toPrimitive ] : 0 } ; 
`${ 0 }${ 0 }${ { [ Symbol . toPrimitive ] : 0 } }` ; 
0 * { [ Symbol . toPrimitive ] : 0 } ; 
0 [ { [ Symbol . toPrimitive ] : 0 } ] ; 