async function x ( ) { for await ( [ 0 ] [ 0 ] of [ , ] ) ; } x ( ) ; 
for ( [ 0 ] [ 0 ] in [ 0 ] ) ; 
for ( [ 0 ] [ 0 ] of [ 0 ] ) ;
for ( [ 0 ] [ 0 ] of [ 0 ] ?? 0 ) ; 
for ( [ , ] [ 0 ] of [ 0 ] ) ;
for ( { 0 : 0 } [ 0 ] of [ 0 ] ) ;
for ( [ 0 , 0 , ] [ 1 ] of [ 0 ] ) ;
let x ; [ { 0 : function ( ) { return [ , ] ; } ( ) [ 0 ] = 0 } = 0 ] = '' ;
let x ; [ { 0 : function ( ) { return [ 0 ] ; } ( ) [ 0 ] = 0 } = 0 ] = '' ;
let x ; [ [ , ] [ 0 ] = 0 ] = `` ;
