( x => [ ... x ] ) ( ) ;
- { ... { get 0 ( ) { x ( ) ; } } } ; 
[ , ... 0 ] ; 
[ , ... function * ( ) { 0 ( ) ; } ( ) ] ;
[ , ... function * ( ) { 0 ( ) ; } ( ) ] ; 
[ , ... function * ( ) { x ( ) ; } ( ) ] ;
[ , ... function * ( ) { yield * 0 ; } ( ) ] ;
[ , ... function * ( ) { yield * x ; } ( ) ] ;
[ , ... function * ( ) { yield * { [ Symbol . iterator ] : async x => 0 } ; } ( ) ] ;
[ , ... function * ( ) { yield 0 . x ??= yield ; } ( ) ] ;
[ , ... function * ( ) { yield x ; } ( ) ] ;
[ ... ! 0 ] ;
[ ... 0 . x ] ;
[ ... 0 ] ; 
[ ... 0n ] ;
[ ... `` . x ] ;
[ ... `` [ 0 % 0 ] ] ;
[ ... `` [ 0 ] ] ;
[ ... function * ( ) { throw 0 ; } ( ) ] ; 
[ ... function * ( ) { yield * 0 ( ) ; } ( ) ] ; 
[ ... function * ( ) { yield * 0 ; } ( ) ] ;
[ ... function * ( ) { yield * function * ( ) { x ( 0 ) ; } ( ) ; } ( ) ] ; 
[ ... function * ( ) { yield * x ; } ( ) ] ; 
[ ... function * ( ) { yield x ; } ( ) ] ; 
[ ... null ] ;
[ ... { [ Symbol . iterator ] : 0 } ] ; 
[ ... { [ Symbol . iterator ] : class { } } ] ; 
[ ... { [ Symbol . iterator ] : function ( ) { } } ] ; 
[ ... { [ Symbol . iterator ] : x => 0 } ] ; 
[ ... { [ Symbol . iterator ] : x => [ ] } ] ;
[ ... { [ Symbol . iterator ] : x => new 0 } ] ; 
[ ... { [ Symbol . iterator ] : x => { } } ] ; 
[ ... { [ Symbol . iterator ] : { } } ] ; 
[ 0 , , ... 0 ] ; 
[ 0 , ... 0 ] ; 
let x ; [ ... x ] ;
var x ; [ ... x ] ;
[ ... { [ Symbol . iterator ] : [ ] } ] ;
[ ... 1n . x ] ;
[ , ... [ 0 ] [ 0 ] ] ;
[ ... { [ Symbol . iterator ] : function * ( ... [ ] ) { let [ ] = 0 ; } } ] ;
[ ... { } . x ] ;
[ ... '' . x ] ;
[ , ... `` [ 0 ] ] ;
[ , ... `` [ 0 % 0 ] ] ;
[ ... true . x ] ;
