0 instanceof '' . x ;
0 instanceof 0 . x ;
0 instanceof 0 ;
0 instanceof 1n . x ;
0 instanceof [ ] ;
0 instanceof true . x ;
0 instanceof { [ Symbol . hasInstance ] : 0 } ;
0 instanceof { } ;
[ ] instanceof async function ( ) { } ;
`${ 0 }` [ 0 ] instanceof { } ;
let x ; x instanceof 0 ;
var x ; x instanceof 0 ;
