~ { [ Symbol . toPrimitive ] : class { } } ; 
0 != { [ Symbol . toPrimitive ] : 0 } ; 
- { [ Symbol . toPrimitive ] : x => [ ] } ; 
- { [ Symbol . toPrimitive ] : 0 } ; 
+ { [ Symbol . toPrimitive ] : 0 } ; 
`${ { [ Symbol . toPrimitive ] : 0 } }` ; 
0 > { [ Symbol . toPrimitive ] : 0 } ; 
0 <= { [ Symbol . toPrimitive ] : 0 } ; 
0 < { [ Symbol . toPrimitive ] : 0 } ; 
- [ { [ Symbol . toPrimitive ] : 0 } ] ; 
0 == { [ Symbol . toPrimitive ] : 0 } ; 
`${ 0 }${ { [ Symbol . toPrimitive ] : 0 } }` ; 
0 + { [ Symbol . toPrimitive ] : 0 } ; 
0 >= { [ Symbol . toPrimitive ] : 0 } ; 
~ { [ Symbol . toPrimitive ] : 0 } ; 
`${ 0 }${ 0 }${ { [ Symbol . toPrimitive ] : 0 } }` ; 
0 * { [ Symbol . toPrimitive ] : 0 } ; 
0 [ { [ Symbol . toPrimitive ] : 0 } ] ;
+ { [ { [ Symbol . toPrimitive ] : 0 } ] : 0 } ;
0 == { [ Symbol . toPrimitive ] : 0 } in [ ] ;
1 < { [ Symbol . toPrimitive ] : 0 } ;
+ { [ Symbol . toPrimitive ] : x => 0n } ;
0 % { [ Symbol . toPrimitive ] : 0 } ;
+ { [ Symbol . toPrimitive ] : x => [ ] } ;
`${ { [ Symbol . toPrimitive ] : false } }` ;
+ { [ Symbol . toPrimitive ] : ( ) => x } ;
~ [ { [ Symbol . toPrimitive ] : 0 } ] ;
+ { [ Symbol . toPrimitive ] : x => function ( ) { } ( ) . x ?. x ** 0 } ;
