for ( '' . x in [ 0 ] ) ; 
for ( 1n . x in [ 0 ] ) ; 
for ( [ , ] [ 0 ] in [ 0 ] ) ; 
for ( [ 0 ] [ 0 ] in [ 0 ] ) ; 
for ( [ ] . x in [ 0 ] ) ; 
for ( [ ] [ 0 ] in [ 0 ] ) ; 
for ( [ ] [ 1 ] in [ 0 ] ) ; 
for ( [ ] in [ 0 ] ) 0 ;
for ( [ ] in [ 0 ] ) ;
for ( [ ] in [ 0 ] ) break ;
for ( [ ] in [ 0 ] ) continue ; 
for ( `${ 0 }` [ 0 ] in [ 0 ] ) ; 
for ( `` [ 0 % 0 ] in [ 0 ] ) ; 
for ( `` [ 0 ] in [ 0 ] ) ; 
for ( null . x in [ 0 ] ) ; 
for ( true . x in [ 0 ] ) ; 
for ( { get 0 ( ) { } , } [ 0 ] in [ 0 ] ) ; 
for ( { get 0 ( ) { } } [ 0 ] in [ 0 ] ) ; 
for ( { set 0 ( x ) { return ; } , } [ 0 ] in [ 0 ] ) ; 
for ( { set 0 ( x ) { return ; } } [ 0 ] in [ 0 ] ) ; 
for ( { set 0 ( x ) { throw 0 ; } , } [ 0 ] in [ 0 ] ) ; 
for ( { set 0 ( x ) { x ( ) ; } , } [ 0 ] in [ 0 ] ) ; 
for ( { set 0 ( x ) { x ( 0 ) ; } } [ 0 ] in [ 0 ] ) ; 
for ( { set 0 ( x ) { } , } [ 0 ] in [ 0 ] ) ; 
for ( { set 0 ( x ) { } } [ 0 ] in [ 0 ] ) ; 
for ( { x : 0 } . x in [ 0 ] ) ; 
for ( { } . x in [ 0 ] ) ; 
for ( { } in [ 0 ] ) 0 ; 
for ( { } in [ 0 ] ) ; 
for ( { } in [ 0 ] ) break ; 
for ( { } in [ 0 ] ) continue ; 
