const x = 0 ; ++ x ;
const x = 0 ; -- x ; 
const x = 0 ; [ x = 0 ] = '' ;
const x = 0 ; [ x = x => 0 ] = `` ; 
const x = 0 ; [ x ] = `` ;
const x = 0 ; [ x ] = `` ; 
const x = 0 ; [ { 0 : x } = 0 ] = '' ;
const x = 0 ; [ { 0 : x } = 0 ] = '' ; 
const x = 0 ; [ { x } = 0 ^ 0 ] = `` ; 
const x = 0 ; for ( x in [ 0 ] ) ; 
const x = 0 ; for ( x of [ 0 ] ) ; 
const x = 0 ; x ++ ; 
const x = 0 ; x = 0 ; 
const x = 0 ; x = x ; 
const x = 0 ; x = { x } = 0 ; 
const x = 0 ; x = { x } = x ; 
const x = 0 ; x ||= 0 ; 
const x = 1n ; ++ x ;
const x = { [ Symbol . toPrimitive ] : 0 } ; ++ x ;
const { ... x } = 0 ; throw x &&= 0 ; 
const { x , } = 0 ; x -- ; 
const { x } = 0 ; for ( x of [ 0 ] ) ; 
for ( const x = 0 ; ; x = 0 ) ; 
x = 0 ; const x = 0 ; 
