const x = 0 ; [ x = 0 ] = '' ; 
const x = 0 ; [ x ] = `` ; 
const x = 0 ; [ { 0 : x } = 0 ] = '' ; 
const x = 0 ; [ { x = 0 ^ 0 === 0 } = 0 ] ; 
const x = 0 ; for ( ; ; x = 0 ) ; 
const x = 0 ; for ( ; ; x = x ) ; 
const x = 0 ; for ( ; ; { x , x } = 0 ) ; 
const x = 0 ; for ( ; ; { x , } = 0 ) ; 
const x = 0 ; for ( ; ; { x } = 0 ) ; 
const x = 0 ; x = 0 ; 
const x = 0 ; x = `` ; 
const x = 0 ; x = x ; 
const x = 0 ; x = { x } = 0 ; 
const x = 0 ; x = { x } = x ; 
const x = 0 ; x ||= 0 ; 
const { ... x } = 0 ; throw x &&= 0 ; 
const { 0 : x , } = 0 ; [ { x , x } = 0 ] ; 
