for ( let x in ! x ) ; 
for ( let x in -- x ) ;
for ( let x in [ x ** 0 ] ) ;
for ( let x in [ x ] ) ;
for ( let x in x %= 0 ^ 0 ) ;
for ( let x in x &&= 0 ) ;
for ( let x in x ) ; 
for ( let x in x . x ) ;
for ( let x in x ||= 0 ) ;
for ( let x of ! x ) ; 
for ( let x of 0 [ 0 % x ] ) ;
for ( let x of 0 [ x % x ] ) ;
for ( let x of 0 [ x ] ) ;
for ( let x of x ) ; 
for ( let x of x ??= 0 ) ;
for ( let x of x [ 0 ] ) ;
for ( let x of { [ 0 ] : x } ) ;
for ( let x of { [ 0 | x ] : x } ) ;
for ( let x of { [ Symbol . iterator ] : function * ( ) { throw x ; } } ) ;
for ( let x of { [ Symbol . iterator ] : function * ( ) { yield * 0 ?. x ( x , ) ; } } ) ;
for ( let x of { [ x | 0 ] : x } ) ;
for ( x ; 0 ; ) ; let x ;
for ( x ; 0 ; 0 ) ; let x ;
for ( x ; ; ) ; let x ;
for ( x ; ; 0 ) ; let x ;
for ( x ; x ; 0 ) ; let x ;
for ( x in [ 0 ] ) ; let x ;
for ( x of [ 0 ] ) ; let x ; 
