class x { static #x = #x in 0 - super . x ; }
class x { static #x = #x in 0 . x ; }
class x { static #x = #x in 0 ; }
class x { static #x = #x in 0 ?. [ super . x ] ; }
class x { static #x = #x in 1n . x ; }
class x { static #x = #x in `${ 0 }` ?. [ 0 ] ; }
class x { static #x = #x in `${ 0 }` [ 0 ] ; }
class x { static #x = #x in `` . x ; }
class x { static #x = #x in `` ?. [ 0 % 0 ] ; }
class x { static #x = #x in `` ?. [ 0 ] ; }
class x { static #x = #x in `` [ 0 % 0 ] ; }
class x { static #x = #x in `` [ 0 ] ; }
class x { static #x = #x in super . x ** 0 ; }
class x { static #x = #x in super . x ; }
class x { static #x = #x in super [ 0 ] ** 0 ; }
class x { static #x = #x in true . x ; }
class x { static #x = #x in void super . x ; }
class x { static #x = #x in { get 0 ( ) { return ; } , } ?. [ 0 ] ; }
class x { static #x = #x in { get 0 ( ) { } , } ?. [ 0 ] ; }
class x { static #x = #x in { set 0 ( x ) { } , } ?. [ 0 ] ; }
class x { static #x = #x in { x } ?. x ?. x ; }
